# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd7421a3def1efa4f119db61d156162630be8c24d3ce9bdee41b0194591ed6b4d1717379640ce0e230a2c5a90e05254ffffeed36150b63ce86c8b36f339700ff

test:
  secret_key_base: 409a002881f0b851bd67eff83a82842530c2a8718e6589d905ce3939c47f499507a4a9b3c65b66ce5e33fb8dfe0a57fe7558943c4451f7f93b4d5cfdbbc10f41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
